#include "UtilsChar.h"

#include <cassert>

#include "natsu.unicode.h"

Regexs::Byte UtilsChar::categoryForLatin1[] = {
	(Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, // 0000 - 0007
	(Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, // 0008 - 000F
	(Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, // 0010 - 0017
	(Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, // 0018 - 001F
	(Regexs::Byte)UnicodeCategory::SpaceSeparator, (Regexs::Byte)UnicodeCategory::OtherPunctuation, (Regexs::Byte)UnicodeCategory::OtherPunctuation, (Regexs::Byte)UnicodeCategory::OtherPunctuation, (Regexs::Byte)UnicodeCategory::CurrencySymbol, (Regexs::Byte)UnicodeCategory::OtherPunctuation, (Regexs::Byte)UnicodeCategory::OtherPunctuation, (Regexs::Byte)UnicodeCategory::OtherPunctuation, // 0020 - 0027
	(Regexs::Byte)UnicodeCategory::OpenPunctuation, (Regexs::Byte)UnicodeCategory::ClosePunctuation, (Regexs::Byte)UnicodeCategory::OtherPunctuation, (Regexs::Byte)UnicodeCategory::MathSymbol, (Regexs::Byte)UnicodeCategory::OtherPunctuation, (Regexs::Byte)UnicodeCategory::DashPunctuation, (Regexs::Byte)UnicodeCategory::OtherPunctuation, (Regexs::Byte)UnicodeCategory::OtherPunctuation, // 0028 - 002F
	(Regexs::Byte)UnicodeCategory::DecimalDigitNumber, (Regexs::Byte)UnicodeCategory::DecimalDigitNumber, (Regexs::Byte)UnicodeCategory::DecimalDigitNumber, (Regexs::Byte)UnicodeCategory::DecimalDigitNumber, (Regexs::Byte)UnicodeCategory::DecimalDigitNumber, (Regexs::Byte)UnicodeCategory::DecimalDigitNumber, (Regexs::Byte)UnicodeCategory::DecimalDigitNumber, (Regexs::Byte)UnicodeCategory::DecimalDigitNumber, // 0030 - 0037
	(Regexs::Byte)UnicodeCategory::DecimalDigitNumber, (Regexs::Byte)UnicodeCategory::DecimalDigitNumber, (Regexs::Byte)UnicodeCategory::OtherPunctuation, (Regexs::Byte)UnicodeCategory::OtherPunctuation, (Regexs::Byte)UnicodeCategory::MathSymbol, (Regexs::Byte)UnicodeCategory::MathSymbol, (Regexs::Byte)UnicodeCategory::MathSymbol, (Regexs::Byte)UnicodeCategory::OtherPunctuation, // 0038 - 003F
	(Regexs::Byte)UnicodeCategory::OtherPunctuation, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, // 0040 - 0047
	(Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, // 0048 - 004F
	(Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, // 0050 - 0057
	(Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::OpenPunctuation, (Regexs::Byte)UnicodeCategory::OtherPunctuation, (Regexs::Byte)UnicodeCategory::ClosePunctuation, (Regexs::Byte)UnicodeCategory::ModifierSymbol, (Regexs::Byte)UnicodeCategory::ConnectorPunctuation, // 0058 - 005F
	(Regexs::Byte)UnicodeCategory::ModifierSymbol, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, // 0060 - 0067
	(Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, // 0068 - 006F
	(Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, // 0070 - 0077
	(Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::OpenPunctuation, (Regexs::Byte)UnicodeCategory::MathSymbol, (Regexs::Byte)UnicodeCategory::ClosePunctuation, (Regexs::Byte)UnicodeCategory::MathSymbol, (Regexs::Byte)UnicodeCategory::Control, // 0078 - 007F
	(Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, // 0080 - 0087
	(Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, // 0088 - 008F
	(Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, // 0090 - 0097
	(Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, (Regexs::Byte)UnicodeCategory::Control, // 0098 - 009F
	(Regexs::Byte)UnicodeCategory::SpaceSeparator, (Regexs::Byte)UnicodeCategory::OtherPunctuation, (Regexs::Byte)UnicodeCategory::CurrencySymbol, (Regexs::Byte)UnicodeCategory::CurrencySymbol, (Regexs::Byte)UnicodeCategory::CurrencySymbol, (Regexs::Byte)UnicodeCategory::CurrencySymbol, (Regexs::Byte)UnicodeCategory::OtherSymbol, (Regexs::Byte)UnicodeCategory::OtherSymbol, // 00A0 - 00A7
	(Regexs::Byte)UnicodeCategory::ModifierSymbol, (Regexs::Byte)UnicodeCategory::OtherSymbol, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::InitialQuotePunctuation, (Regexs::Byte)UnicodeCategory::MathSymbol, (Regexs::Byte)UnicodeCategory::DashPunctuation, (Regexs::Byte)UnicodeCategory::OtherSymbol, (Regexs::Byte)UnicodeCategory::ModifierSymbol, // 00A8 - 00AF
	(Regexs::Byte)UnicodeCategory::OtherSymbol, (Regexs::Byte)UnicodeCategory::MathSymbol, (Regexs::Byte)UnicodeCategory::OtherNumber, (Regexs::Byte)UnicodeCategory::OtherNumber, (Regexs::Byte)UnicodeCategory::ModifierSymbol, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::OtherSymbol, (Regexs::Byte)UnicodeCategory::OtherPunctuation, // 00B0 - 00B7
	(Regexs::Byte)UnicodeCategory::ModifierSymbol, (Regexs::Byte)UnicodeCategory::OtherNumber, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::FinalQuotePunctuation, (Regexs::Byte)UnicodeCategory::OtherNumber, (Regexs::Byte)UnicodeCategory::OtherNumber, (Regexs::Byte)UnicodeCategory::OtherNumber, (Regexs::Byte)UnicodeCategory::OtherPunctuation, // 00B8 - 00BF
	(Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, // 00C0 - 00C7
	(Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, // 00C8 - 00CF
	(Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::MathSymbol, // 00D0 - 00D7
	(Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::UppercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, // 00D8 - 00DF
	(Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, // 00E0 - 00E7
	(Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, // 00E8 - 00EF
	(Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::MathSymbol, // 00F0 - 00F7
	(Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, (Regexs::Byte)UnicodeCategory::LowercaseLetter, // 00F8 - 00FF
};

UnicodeCategory CharUnicodeInfo::InternalGetUnicodeCategory(int ch)
{
	return ((UnicodeCategory)_s_InternalGetCategoryValue(ch, UNICODE_CATEGORY_OFFSET));
}

UnicodeCategory UtilsChar::GetLatin1UnicodeCategory(wchar_t ch)
{
	if (IsLatin1(ch))
		assert("Char.GetLatin1UnicodeCategory(): ch should be <= 007f");
	return (UnicodeCategory)(categoryForLatin1[(int)ch]);
}
